---
title: "Client Report - What's in a Name?"
subtitle: "Unit 1 Task 2"
author: "Ethan Neunhoffer"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```

```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
df = pl.read_csv("https://posit.byui.edu/content/0d43d66f-d3b7-4c43-8c36-52e3ed69e7f1/names_year_csv.csv")
```

## QUESTION 1

<!-- Make sure at least one of your charts includes reference marks!! -->

__How does your name at your birth year compare to its use historically? Your must provide a chart. The years labels on your charts should not include a comma.__ 

It looks like the year that I was born the name Ethan was used a total of 21,361 times. We see a very severe dropoff the older the years go with the earliest years in the data set around 1930-1950 the name was only recorded 5 times in the whole year.

_type your results and analysis here_

```{python}
# Q1

ethan = df.filter((pl.col("name") == "Ethan") & (pl.col("year") == 2003)).sort("Total", descending=True).head(1)
ethan2 = df.filter(((pl.col("name") == "Ethan") & (pl.col("year") < 2024) & (pl.col("year") > 1910))).sort("Total", descending=True)

print(ethan)
print(ethan2)
```


## QUESTION 2

__Think of a unique name from a famous movie. Plot the usage of that name and see how changes line up with the movie release. Does it look like the movie had an effect on usage?__  

I actually decided to use my name because it is from a famous movie specifically mission impossible. It looks like around the movies release in 1996 the name remained relativly the same then around the year 2000 it spiked a lot more. Seemingly because the sequel releases of the movie made the name more well known and therefore more used.

_type your results and analysis here_

```{python}
# Q2
ethan = df.filter((pl.col("name") == "Ethan") & (pl.col("year").is_in([1993, 1996, 1999, 2002]))).sort("Total", descending=True)
print (ethan)
```

## QUESTION 3

__Mary, Martha, Peter, and Paul are all Christian names. From 1920 - 2000, compare the name usage of each of the four names in a single chart. What trends do you notice?__  

It seems that the names are slowly dying off over the years and becoming less and less popular. The most notaciable dropoff beeing Mary going from over 70,000 to near 6,000 in recent years. Also noticed that the name Martha has consistenctly remained the least used amoung the four. Meanwhile Peter is the most stable not changing much.

_type your results and analysis here_

```{python}
# Q3
fournames = df.filter((pl.col("name").is_in(["Mary", "Martha", "Peter", "Paul"])) & (pl.col("year") < 2000) & (pl.col("year") > 1920)).sort("year")

with pl.Config(tbl_rows=200):
    print(fournames)
```
<!-- Make sure at least one of your charts includes reference marks!! -->